### ISSUE TITLE
Filename issues

### ISSUE THREAD

**Issue by Ansalpandey** [Ankitkumar1100/C_4th_assignment#1]
Hi! Ankit, I seen your code files and checked your code and got some formatting and file naming issues.

Considering this I want to contribute to it and make changes.

**Comment by Ansalpandey** [comment]
Thanks for assigning me

**Comment by Ansalpandey110043** [comment]
#2

**Comment by Ansalpandey** [comment]
I have changed the code you can review it here #3.
